version: "3.8"

services:
  # RabbitMQ for asynchronous messaging between services
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672" # RabbitMQ port
      - "15672:15672" # RabbitMQ management interface
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      # RABBITMQ_DISK_FREE_LIMIT: 10GB
      # RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 0.9
    volumes:
      - ./.config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
  # Milvus for vector storage of face embeddings
  # milvus:
  #   image: milvusdb/milvus:v2.2.9
  #   ports:
  #     - "19530:19530"
  #     - "9091:9091"

  # Global database
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - .data/db/mongo:/data/db
    networks:
      - app-network
  # RTSP Service (Camera 1) with HTTP preview
  # [Deprecated] Using device-rest-service and device-stream-service instead
  # rtsp-device-service:
  #   build: ./services/rtsp-service
  #   environment:
  #     APP_HOST: "rtsp-device-service"
  #     APP_PORT: 80
  #     MONGODB_URI: "mongodb://root:example@mongodb/test?authSource=admin"
  #     RABBIT_MQ_URI: "amqp://user:password@rabbitmq:5672/%2F"
  #   # ports:
  #   #   - "8100:80"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "4"
  #         memory: 2G
  #   depends_on:
  #     - rabbitmq
  #     - mongodb

  device-stream-service:
    build: ./services/device-stream-service
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://root:example@mongodb/devices?authSource=admin"
      RABBIT_MQ_URI: "amqp://user:password@rabbitmq:5672/%2F"
      STREAM_OUTPUT_DIRECTORY: "./.data"
    ports:
      - 3072:3004
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - devices-network
      - app-network
    cpus: 4

  # Face Detection Service
  face-detection-service:
    build: ./services/face-detection-service
    environment:
      RABBIT_MQ_URI: "amqp://user:password@rabbitmq:5672/%2F"
      FACE_DETECT_MODEL: "fastmtcnn"
    restart: always
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "1"
          memory: 200M
      # resources:
      #   reservations:
      #     devices:
      #       - driver: nvidia
      #         count: "${CUDA_ENABLED:-0}"
      #         capabilities: [gpu]
    depends_on:
      - rabbitmq
    volumes:
      - ./.data/cache/torch:/root/.cache/torch
    networks:
      - app-network

  face-recognition-web-service:
    build: ./services/face-recognition-web-service
    environment:
      - MILVUS_CONNECTION_URI=http://milvus-standalone:19530
      - PRIMARY_EMBEDDING_COLLECTION_NAME=primary_face_embeddings
      - HISTORY_FACE_COLLECTION_NAME=history_face_embeddings
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 1024M
    restart: always
    ports:
      - 8555:80
    volumes:
      - .data/recognition_data:/code/.data
      - ./.data/cache/torch:/root/.cache/torch
    depends_on:
      - rabbitmq
      - milvus-etcd
      - milvus-minio
      - milvus-standalone
    networks:
      - app-network
      - devices-network

  ui-web-service:
    build: ./services/ui
    # ports:
    #   - 8080:80

  # Face Recognition Service
  face-recognition-service:
    build: ./services/face-recognition-service
    environment:
      # RABBITMQ_HOST: rabbitmq
      # RABBITMQ_QUEUE_IN: detected_faces
      # RABBITMQ_QUEUE_OUT: recognition_results
      # MILVUS_HOST: milvus
      # MILVUS_PORT: 19530
      RABBIT_MQ_URI: "amqp://user:password@rabbitmq:5672/%2F"
      MILVUS_CONNECTION_URI: "http://milvus-standalone:19530"
      RABBIT_MQ_FACE_RECOGNITION_EXCHANGE_NAME: "detect.recognition.direct"
      RABBIT_MQ_FACE_RECOGNITION_QUEUE_NAME: "face_recognition"
      LOGGING_API_BASE_URL: "http://logging-service:3234"
    restart: always
    depends_on:
      - rabbitmq
      - milvus-etcd
      - milvus-minio
      - milvus-standalone
    networks:
      - app-network
      - devices-network
    volumes:
      - ./.data/cache/torch:/root/.cache/torch
      - ./.data/recognition-service-output/:/code/.data

  device-rest-service:
    build: ./services/device-rest-service
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://root:example@mongodb:27017/devices?authSource=admin"
    restart: always
    ports:
      - 3015:3000
    depends_on:
      - mongodb
    networks:
      - app-network
      - devices-network

  user-service:
    build: ./services/user-service
    environment:
      PORT: 3192
      MONGODB_URI: "mongodb://root:example@mongodb:27017/users?authSource=admin"
      JWT_SECRET_KEY: "e046dc12-31bf-47a2-ab6e-941e76272718"
      JWT_TOKEN_EXPIRED_IN: "1200d"
    restart: always
    ports:
      - 3192:3192
    depends_on:
      - mongodb
    networks:
      - app-network
      - devices-network

  logging-service:
    build: ./services/logging-service
    environment:
      APP_PORT: 3234
      MONGODB_CONNECTION_STRING: "mongodb://root:example@mongodb:27017/logging?authSource=admin"
      # JWT_SECRET_KEY: "e046dc12-31bf-47a2-ab6e-941e76272718"
      # JWT_TOKEN_EXPIRED_IN: "1200d"
    restart: always
    ports:
      - 3234:3234
    depends_on:
      - mongodb
    networks:
      - app-network
      - devices-network

  #==========================
  #  * Milvus Database
  #   configuration
  #
  #==========================
  milvus-etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/.data/milvus/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app-network

  milvus-minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/.data/milvus/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app-network

  milvus-standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.15
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: milvus-etcd:2379
      MINIO_ADDRESS: milvus-minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/.data/milvus/main:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "milvus-etcd"
      - "milvus-minio"
    networks:
      - app-network

  milvus-attu:
    container_name: milvus-attu
    image: zilliz/attu:v2.4
    environment:
      - MILVUS_URL=milvus-standalone:19530
    ports:
      - "3168:3000"
    depends_on:
      - "milvus-standalone"
    networks:
      - app-network

  #==========================
  #  * Nginx API Gateway
  #
  #==========================
  nginx:
    image: nginx:latest
    volumes:
      - .config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      # - rtsp-device-service
      - face-recognition-web-service
      - ui-web-service
    networks:
      - app-network
      - devices-network

volumes:
  mongo-data:

networks:
  default:
    name: milvus
  devices-network:
    driver: bridge
  app-network:
    driver: bridge
